trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Do the build" # Basic build step

  - stage: DevDeploy
    jobs:
      - deployment: DevDeployJob
        environment: Dev # Ensure this matches exactly with the environment name in Azure DevOps
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to Dev environment" # Deployment to Dev

  - stage: QADeploy
    jobs:
      - deployment: QADeployJob
        environment: QA # Ensure this matches exactly with the environment name in Azure DevOps
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to QA environment" # Deployment to QA

